repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3.10  # or whichever Python version you're using

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        args: ["--max-line-length=79"]
