import frappe

@frappe.whitelist(allow_guest=True)
def sales_summary_with_no_auth():
    return [
  {
    "branch_id": "A",
    "branch_name": "Downtown Clinic",
    "location": "123 Main St, City Center",
    "revenue": 1200000,
    "inventory_value": 250000,
    "patients_served": 60,
    "items_sold": 200,
    "staff_count": 15,
    "avg_patient_wait_time": "15 minutes",
    "operational_hours": "8 AM - 6 PM",
    "branch_manager": "John Doe",
    "year_to_date_revenue": 8000000,
    "customer_satisfaction_score": 4.5,
    "net_profit": 350000,
    "marketing_spend": 50000,
    "new_patient_signups": 25,
    "revenue_growth_percentage": 12.5,
    "total_expenses": 850000,
    "average_transaction_value": 20000,
    "inventory_turnover_rate": 3.2,
    "service_type": "General Healthcare"
  },
  {
    "branch_id": "B",
    "branch_name": "Uptown Health Center",
    "location": "456 Elm St, Uptown District",
    "revenue": 1800000,
    "inventory_value": 320000,
    "patients_served": 85,
    "items_sold": 250,
    "staff_count": 20,
    "avg_patient_wait_time": "12 minutes",
    "operational_hours": "9 AM - 7 PM",
    "branch_manager": "Jane Smith",
    "year_to_date_revenue": 9500000,
    "customer_satisfaction_score": 4.7,
    "net_profit": 500000,
    "marketing_spend": 75000,
    "new_patient_signups": 40,
    "revenue_growth_percentage": 15.3,
    "total_expenses": 1300000,
    "average_transaction_value": 21176,
    "inventory_turnover_rate": 4.4,
    "service_type": "Specialized Healthcare"
  },
  {
    "branch_id": "C",
    "branch_name": "Westside Medical Center",
    "location": "789 Oak St, Westside",
    "revenue": 2300000,
    "inventory_value": 450000,
    "patients_served": 110,
    "items_sold": 300,
    "staff_count": 25,
    "avg_patient_wait_time": "10 minutes",
    "operational_hours": "7 AM - 5 PM",
    "branch_manager": "Alice Johnson",
    "year_to_date_revenue": 11000000,
    "customer_satisfaction_score": 4.8,
    "net_profit": 750000,
    "marketing_spend": 100000,
    "new_patient_signups": 55,
    "revenue_growth_percentage": 18.7,
    "total_expenses": 1550000,
    "average_transaction_value": 20909,
    "inventory_turnover_rate": 5.2,
    "service_type": "Emergency Care"
  },
  {
    "branch_id": "D",
    "branch_name": "Eastside Health Hub",
    "location": "101 Pine St, Eastside",
    "revenue": 900000,
    "inventory_value": 150000,
    "patients_served": 40,
    "items_sold": 120,
    "staff_count": 10,
    "avg_patient_wait_time": "20 minutes",
    "operational_hours": "8 AM - 4 PM",
    "branch_manager": "Michael Davis",
    "year_to_date_revenue": 4500000,
    "customer_satisfaction_score": 4.2,
    "net_profit": 250000,
    "marketing_spend": 30000,
    "new_patient_signups": 15,
    "revenue_growth_percentage": 8.3,
    "total_expenses": 650000,
    "average_transaction_value": 22500,
    "inventory_turnover_rate": 2.6,
    "service_type": "General Healthcare"
  },
  {
    "branch_id": "E",
    "branch_name": "Northview Wellness Clinic",
    "location": "202 Maple St, Northview",
    "revenue": 1500000,
    "inventory_value": 300000,
    "patients_served": 75,
    "items_sold": 180,
    "staff_count": 18,
    "avg_patient_wait_time": "18 minutes",
    "operational_hours": "9 AM - 6 PM",
    "branch_manager": "Emily White",
    "year_to_date_revenue": 7000000,
    "customer_satisfaction_score": 4.6,
    "net_profit": 400000,
    "marketing_spend": 60000,
    "new_patient_signups": 30,
    "revenue_growth_percentage": 10.2,
    "total_expenses": 1100000,
    "average_transaction_value": 20000,
    "inventory_turnover_rate": 3.9,
    "service_type": "Wellness & Preventive Care"
  }
]



@frappe.whitelist()
def sales_summary_with_auth():
    return [
  {
    "branch_id": "A",
    "branch_name": "Downtown Clinic",
    "location": "123 Main St, City Center",
    "revenue": 1200000,
    "inventory_value": 250000,
    "patients_served": 60,
    "items_sold": 200,
    "staff_count": 15,
    "avg_patient_wait_time": "15 minutes",
    "operational_hours": "8 AM - 6 PM",
    "branch_manager": "John Doe",
    "year_to_date_revenue": 8000000
  },
  {
    "branch_id": "B",
    "branch_name": "Uptown Health Center",
    "location": "456 Elm St, Uptown District",
    "revenue": 1800000,
    "inventory_value": 320000,
    "patients_served": 85,
    "items_sold": 250,
    "staff_count": 20,
    "avg_patient_wait_time": "12 minutes",
    "operational_hours": "9 AM - 7 PM",
    "branch_manager": "Jane Smith",
    "year_to_date_revenue": 9500000
  },
  {
    "branch_id": "C",
    "branch_name": "Westside Medical Center",
    "location": "789 Oak St, Westside",
    "revenue": 2300000,
    "inventory_value": 450000,
    "patients_served": 110,
    "items_sold": 300,
    "staff_count": 25,
    "avg_patient_wait_time": "10 minutes",
    "operational_hours": "7 AM - 5 PM",
    "branch_manager": "Alice Johnson",
    "year_to_date_revenue": 11000000
  },
  {
    "branch_id": "D",
    "branch_name": "Eastside Health Hub",
    "location": "101 Pine St, Eastside",
    "revenue": 900000,
    "inventory_value": 150000,
    "patients_served": 40,
    "items_sold": 120,
    "staff_count": 10,
    "avg_patient_wait_time": "20 minutes",
    "operational_hours": "8 AM - 4 PM",
    "branch_manager": "Michael Davis",
    "year_to_date_revenue": 4500000
  },
  {
    "branch_id": "E",
    "branch_name": "Northview Wellness Clinic",
    "location": "202 Maple St, Northview",
    "revenue": 1500000,
    "inventory_value": 300000,
    "patients_served": 75,
    "items_sold": 180,
    "staff_count": 18,
    "avg_patient_wait_time": "18 minutes",
    "operational_hours": "9 AM - 6 PM",
    "branch_manager": "Emily White",
    "year_to_date_revenue": 7000000
  }
]
